version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Restoring dependencies..."
      - dotnet restore
  build:
    commands:
      - echo "Building backend..."
      - dotnet publish -c Release -o published
  post_build:
    commands:
      - echo "Fetching SSH Key from Secrets Manager..."
      - aws secretsmanager get-secret-value --secret-id SSH_PRIVATE_KEY --query SecretString --output text | jq -r '.SSH_PRIVATE_KEY' | tr -d '\r' > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - echo "Reformatting SSH Key..."
      - openssl rsa -in /root/.ssh/id_rsa -out /root/.ssh/id_rsa.new -nocrypt
      - mv /root/.ssh/id_rsa.new /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - echo "Verifying SSH Key Format..."
      - cat /root/.ssh/id_rsa | head -n 5  # Debug
      - file /root/.ssh/id_rsa  # Controlla il formato della chiave
      - echo "Testing SSH connection..."
      - ssh -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa ec2-user@16.170.247.142 "echo 'Connected successfully!'"