version: 0.2

env:
  secrets-manager:
    SSH_PRIVATE_KEY: "SSH_PRIVATE_KEY:SSH_PRIVATE_KEY"

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Restoring dependencies..."
      - dotnet restore
  
  build:
    commands:
      - echo "Building backend..."
      - dotnet publish -c Release -o published
  
  post_build:
    commands:
      - echo "Decoding SSH key..."
      - echo "$SSH_PRIVATE_KEY" | base64 --decode > /root/private_key.pem
      - chmod 600 /root/private_key.pem

      - echo "Deploying build artifacts to EC2..."
      - scp -i /root/private_key.pem -r published/* ec2-user@16.170.247.142:/var/www/backend/

      - echo "Restarting backend service..."
      - ssh -i /root/private_key.pem ec2-user@16.170.247.142 "sudo systemctl restart backend.service"

      - echo "Cleaning up private key..."
      - rm -f /root/private_key.pem